// Generated by LiveScript 1.4.0
(function(){
  var install_edvertisements_web, install_edvertisements_feed, download_source, out$ = typeof exports != 'undefined' && exports || this;
  out$.install_edvertisements_web = install_edvertisements_web = function(){
    return alert('Coming soon (paper is undergoing review but extension is not anonymized)');
  };
  out$.install_edvertisements_feed = install_edvertisements_feed = function(){
    return alert('Coming soon (paper is undergoing review but extension is not anonymized)');
  };
  out$.download_source = download_source = function(){
    return alert('Coming soon (paper is undergoing review but source code is not anonymized)');
  };
}).call(this);
