// Generated by LiveScript 1.4.0
(function(){
  var install_edvertisements_web, install_edvertisements_feed, download_source, out$ = typeof exports != 'undefined' && exports || this;
  out$.install_edvertisements_web = install_edvertisements_web = function(){
    return alert('Coming soon (paper is undergoing review but extension is not anonymized)');
  };
  out$.install_edvertisements_feed = install_edvertisements_feed = function(){
    var url;
    if ((typeof chrome != 'undefined' && chrome !== null) && chrome.webstore != null && chrome.webstore.install != null) {
      return chrome.webstore.install(url = 'https://chrome.google.com/webstore/detail/hccgihpfbdppifbnnlcgllbominjfgak');
    } else {
      return alert('Please visit this page with Google Chrome to install the extension');
    }
  };
  out$.download_source = download_source = function(){
    return alert('Coming soon (paper is undergoing review but source code is not anonymized)');
  };
}).call(this);
